/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lahenry.nimbus.gui.components;

import com.lahenry.nimbus.accountmanager.AccountInfo;
import com.lahenry.nimbus.gui.helpers.IconFactory;
import com.lahenry.nimbus.utils.Logit;
import javax.swing.ImageIcon;

/**
 *
 * @author henry
 */
public class AccountInfoButton extends javax.swing.JButton
{
    private static final Logit LOG = Logit.create(AccountInfoButton.class.getName());

    protected final AccountInfo m_account;

    /**
     * Creates new form AccountInfoPanel
     */
    public AccountInfoButton(final AccountInfo accountInfo)
    {
        initComponents();

        m_account = accountInfo;

        //String label = getHtmlLabel(accountInfo.getName() + " " + accountInfo.getId());
        //lblLabel.setText(label);
        lblLabel.setText(accountInfo.getName());

        setupIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblIcon = new javax.swing.JLabel();
        lblLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setText("icon");
        lblIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));
        lblIcon.setMaximumSize(new java.awt.Dimension(96, 64));
        lblIcon.setMinimumSize(new java.awt.Dimension(96, 64));
        lblIcon.setPreferredSize(new java.awt.Dimension(96, 64));
        add(lblIcon, java.awt.BorderLayout.CENTER);

        lblLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLabel.setText("label");
        lblLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    protected String getHtmlLabel(String str)
    {
        final int max_width = getSize().width;

        return "<html><body style='text-align:center; width:"+Integer.toString(max_width)+"px'><p>"+str+"</p></body></html>";
    }

    protected void setupIcon()
    {
        ImageIcon icon = IconFactory.get(m_account.getType(), IconFactory.IconSize.LARGE);

        lblIcon.setIcon(icon);
        lblIcon.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLabel;
    // End of variables declaration//GEN-END:variables
}
