/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lahenry.nimbus.gui;

import com.lahenry.nimbus.gstreamer.GStreamerAudio;
import com.lahenry.nimbus.gstreamer.GStreamerMedia;
import com.lahenry.nimbus.gstreamer.GStreamerVideo;
import com.lahenry.nimbus.gui.helpers.BusyTaskCursor;
import com.lahenry.nimbus.mainapp.AppInfo;
import com.lahenry.nimbus.utils.Logit;
import java.awt.Component;
import java.io.InputStream;

/**
 *
 * @author henry
 */
public class GStreamerFrame extends javax.swing.JFrame
{
    private static final Logit LOG = Logit.create(GStreamerFrame.class.getName());

    private GStreamerMedia m_gst;

    /**
     * Creates new form GStreamerFrame
     */
    public GStreamerFrame ()
    {
        initComponents();
    }

    public static void show(final Component parent, final String title, final InputStream istream)
    {
        LOG.entering("show", new Object[]{istream});

        BusyTaskCursor.doTask(parent, new BusyTaskCursor.IBusyTask()
        {
            @Override
            public void run()
            {
                GStreamerFrame frame = null;

                try
                {
                    frame = new GStreamerFrame();

                    frame.setTitle(title);

                    frame.init(title, istream);

                    frame.setVisible(true);

                    //frame.play();
                }
                catch (Exception ex)
                {
                    LOG.throwing("show", ex);

                    if (frame != null)
                    {
                        frame.dispose();
                    }
                }
            }
        });

    }

    public void init(final String title, final InputStream istream)
    {
        //m_gst = new GStreamerAudio(title, istream);
        m_gst = new GStreamerVideo(title, istream);
        m_gst.init();
    }

    public void play()
    {
        LOG.info("Playing stream");
        m_gst.play();
    }

    public void stop()
    {
        LOG.info("Stopping stream");
        m_gst.stop();
    }

    @Override
    public void setTitle(String title)
    {
        final String APP_NAME = " - " + AppInfo.NAME;

        if (title.endsWith(APP_NAME))
            super.setTitle(title);
        else
            super.setTitle(title + APP_NAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        LOG.entering("formWindowClosing");

        m_gst.close();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GStreamerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GStreamerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GStreamerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GStreamerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run ()
            {
                new GStreamerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
