/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lahenry.nimbus.gui;

import com.lahenry.nimbus.gui.helpers.BusyTaskCursor;
import com.lahenry.nimbus.utils.Logit;
import java.awt.Component;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author henry
 */
public class ImageViewerFrame extends javax.swing.JFrame
{
    private static final Logit LOG = Logit.create(ImageViewerFrame.class.getName());

    /**
     * Creates new form ImageViewerFrame
     */
    protected ImageViewerFrame ()
    {
        initComponents();
    }

    public static void show(final Component parent, final String title, final InputStream istream)
    {
        LOG.entering("show", new Object[]{istream});

        BusyTaskCursor.doTask(parent, new BusyTaskCursor.IBusyTask()
        {
            @Override
            public void run()
            {
                ImageViewerFrame frame = new ImageViewerFrame();

                try
                {
                    frame.setTitle(title);

                    frame.setImage(istream);

                    frame.setVisible(true);
                }
                catch (IOException ex)
                {
                    LOG.throwing("show", ex);
                    
                    frame.dispose();

                    JOptionPane.showMessageDialog(
                        null,
                        "Failed to load image. Error: "+ex.getMessage(),
                        "Image error",
                        JOptionPane.ERROR_MESSAGE);

                    LOG.info("Failed to show image");
                }
            }
        });
    }

    protected void setImage(InputStream istream) throws IOException
    {
        pnlImage.setImage(istream);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlScroll = new javax.swing.JScrollPane();
        pnlImage = new com.lahenry.nimbus.gui.components.ImagePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlScroll.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlScroll.setViewportView(pnlImage);

        getContentPane().add(pnlScroll, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ImageViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ImageViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ImageViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ImageViewerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run ()
            {
                new ImageViewerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.lahenry.nimbus.gui.components.ImagePanel pnlImage;
    private javax.swing.JScrollPane pnlScroll;
    // End of variables declaration//GEN-END:variables
}
